//Recipes
export const GET_RECIPE = "GET RECIPE";
export const GET_RECIPES_SUCCESS = "GET RECIPES SUCCESS";
export const GET_SINGLE_RECIPES_SUCCESS = "GET SINGLE RECIPE SUCCESS";
export const ADD_RECIPE_INIT = "ADD RECIPE INIT";
export const GET_RECIPE_INIT = "GET RECIPE INIT";
export const ADD_RECIPE = "ADD RECIPE";
export const ADD_RECIPE_SUCCESS = "ADD RECIPE SUCCESS";
export const LOADING = "LOADING";
export const ERROR_OCCURED = "ERROR_OCCURED";export const DELETE_RECIPE_INIT = "DELETE RECIPE INIT";
export const DELETE_RECIPE_SUCCESS = "DELETE RECIPE SUCCESS";
export const EDIT_RECIPE_DONE = "EDIT RECIPE DONE";
export const EDIT_RECIPE_INIT = "EDIT RECIPE INIT";
export const EDIT_RECIPE_SUCCESS = "EDIT RECIPE SUCCESS";
export const GET_USER_RECIPES = "GET USER RECIPES";
export const GET_USER_RECIPES_SUCCESS = "GET USER RECIPES SUCCESS";
export const GET_SINGLE_RECIPE_SUCCESS = "GET SINGLE RECIPE SUCCESS";


// AUTH
export const AUTH_START = "AUTH START";
export const AUTH_SUCCESS = "AUTH SUCCESS";
export const AUTH_FAILED = "AUTH FAILED";
export const LOGOUT_SUCCESS = "LOGOUT SUCCESS";
export const TOGGLE_AUTH = "TOGGLE AUTH";
export const LOAD_AUTH_USER_START = "LOAD_AUTH_USER_START";
export const LOAD_AUTH_USER_SUCCESS = "LOAD_AUTH_USER_SUCCESS";
export const LOAD_AUTH_USER_FAILED = "LOAD_AUTH_USER_FAILED";